"""
5. built in exceptions

In python, all exceptions must be instances of a class that derives from BaseException. In a try statement with  an
except clause that mentions a particular class, that clause also handles any exception classes derived from that class
(but not exception classes from which it is derived). Two exception classes derived from that class (but not exception
class from which it is derived). Two exception classes that are not related via subclassing are never equivalent, even
if they have the same name.

The built-in exceptions listed below can be generated by the interpreter or built-in functions. Except where mentioned,
they have an "associated value" indicating the detailed cause of the error. This may be a string or a tuple of several
items of information (e.g. an error code and a string explaining the code). The associated value is usually passed as
arguments to the exception classes constructor.

User code can raise built-in exceptions. this can be sued to test an exception handler or to report an error condition
"just like" the situation in which the interpreter raise the same exception; but beware that there is noting to
prevent user code from raising an inappropriate error.

5.4 exception hierarchy

BaseException
    - SystemExit
    - KeyboardInterrupt
    - GeneratorExit
    - Exception
        - StopIteration
        - StopAsyncIteration
        - ArithmeticError
            - FloatingPointError
            - OverflowError
            - ZeroDivisionError
        - AssertionError
        - AttributeError
        - BufferError
        - EOFError
        - ImportError
            - ModuleNotFoundError
        - LookupError
            - IndexError
            - KeyError
        - MemoryError
        - NameError
            - UnboundLocalError
        - OSError
            - BlockingIOError
            - ChildProcessError
            - ConnectionError
                - BrokenPipeError
                - ConnectionAbortedError
                - ConnectionRefusedError
                - ConnectionResetError
            - FileExistsError
            - FileNotFoundError
            - InterruptedError
            - IsADirectoryError
            - NotADirectoryError
            - PermissionError
            - ProcessLookupError
            - TimeoutError
        - ReferenceError
        - RuntimeError
            - NotImplementedError
            - RecursionError
        - SyntaxError
            - IndentationError
                - TabError
        - SystemError
        - TypeError
        - ValueError
            - UnicodeError
                - UnicodeDecodeError
                - UnicodeEncodeError
                - UnicodeTranslateError
        - Warning
            - DeprecationWarning
            - PendingDeprecationWarning
            - RuntimeWarning
            - SyntaxWarning
            - UserWarning
            - FutureWarning
            - ImportWarning
            - UnicodeWarning
            - BytesWarning
            - ResourceWarning
"""