"""
- System design basic
    - Why system design interviews?
    - System design basics
    - Consistent hashing
    - CAP theorem
    - Load balancing
    - Caching
    - Data partitioning
    - Indexes
    - Proxies
    - Queues
    - Redundancy and replication
    - SQL or noSQL

- System design problems
    - System design interview: A step by step guide
    - 1. Designing a URL shortening service like TinyURL
    - 2. Designing Pastebin
    - 3. Design Instagram
    - 4. Designing Dropbox
    - 5. Designing Facebook Message
    - 6. Designing Twitter
    - 7. Designing Youtube
    - 8. Designing Typeahead suggestion
    - 9. Designing Twitter search
    - 10. Designing a web crawler
    - 11. Designing Facebook's newsfeed
    - 12. Designing Yelp
    - 13. Designing uber backend
"""